channels:
- conda-forge
dependencies:
- python=3.6
- tensorflow
- bokeh>=1.0.1
- cython>=0.29
- future>=0.17.0
- h5py>=2.8.0
- ipython>=7.1.1
- ipyparallel>=6.2.3
- jupyter>=1.0.0
- keras
- matplotlib>=2.0.2
- nose>=1.3.7
- numpy>=1.14
- opencv>=3.2
- peakutils>=1.3.0
- pims>=0.4.1
- scipy>=1.0
- scikit-image>=0.14.1
- scikit-learn>=0.20.0
- spyder>=3.3.1
- tifffile>=0.15.1
- tqdm>=4.28.1
- tornado=4.5
- pandas>=0.20.1
- pytest
- pymsgbox>=1.0.6
- imreg_dft>=2.0.0
- libtiff>=4.0.9
- sphinx=1.7.1
- sphinx_rtd_theme>=0.4.2
- qt=5.9
- pip:
     - "git+https://github.com/flatironinstitute/CaImAn.git@7dc5b42ab06c6a6b86ff1520dfc5b2334f335a78"
     - "git+https://github.com/inscopix/isx-cnmfe-wrapper.git@v1.2"
